// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://mjvoqtjcgmyhobqshqtb.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qdm9xdGpjZ215aG9icXNocXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMyMDMxMTUsImV4cCI6MjA0ODc3OTExNX0.lvYrija87bJq2xLGdVTCC0U1G-U_zEmJMjKJ1BsT7T4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);